package com.ghj.chat.protocol;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ack_message.proto

public final class AckMessageProto {
  private AckMessageProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface AckMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:AckMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 id = 1;</code>
     */
    long getId();

    /**
     * <code>int32 code = 2;</code>
     */
    int getCode();

    /**
     * <code>string content = 3;</code>
     */
    java.lang.String getContent();
    /**
     * <code>string content = 3;</code>
     */
    com.google.protobuf.ByteString
        getContentBytes();

    /**
     * <code>int64 matchMessageId = 4;</code>
     */
    long getMatchMessageId();

    /**
     * <code>int32 toUserId = 5;</code>
     */
    int getToUserId();

    /**
     * <code>int32 fromUserId = 6;</code>
     */
    int getFromUserId();

    /**
     * <code>int32 associatedGroupId = 7;</code>
     */
    int getAssociatedGroupId();

    /**
     * <code>.AckMessage.MessageDirect messageDirect = 8;</code>
     */
    int getMessageDirectValue();
    /**
     * <code>.AckMessage.MessageDirect messageDirect = 8;</code>
     */
    AckMessageProto.AckMessage.MessageDirect getMessageDirect();

    /**
     * <code>int32 machineSerialNumber = 9;</code>
     */
    int getMachineSerialNumber();
  }
  /**
   * <pre>
   * class Person
   * </pre>
   *
   * Protobuf type {@code AckMessage}
   */
  public  static final class AckMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:AckMessage)
      AckMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use AckMessage.newBuilder() to construct.
    private AckMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AckMessage() {
      content_ = "";
      messageDirect_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new AckMessage();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private AckMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              id_ = input.readInt64();
              break;
            }
            case 16: {

              code_ = input.readInt32();
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              content_ = s;
              break;
            }
            case 32: {

              matchMessageId_ = input.readInt64();
              break;
            }
            case 40: {

              toUserId_ = input.readInt32();
              break;
            }
            case 48: {

              fromUserId_ = input.readInt32();
              break;
            }
            case 56: {

              associatedGroupId_ = input.readInt32();
              break;
            }
            case 64: {
              int rawValue = input.readEnum();

              messageDirect_ = rawValue;
              break;
            }
            case 72: {

              machineSerialNumber_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return AckMessageProto.internal_static_AckMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return AckMessageProto.internal_static_AckMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              AckMessageProto.AckMessage.class, AckMessageProto.AckMessage.Builder.class);
    }

    /**
     * Protobuf enum {@code AckMessage.MessageDirect}
     */
    public enum MessageDirect
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>PERSONAL = 0;</code>
       */
      PERSONAL(0),
      /**
       * <code>GROUP = 1;</code>
       */
      GROUP(1),
      /**
       * <code>SERVER = 2;</code>
       */
      SERVER(2),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>PERSONAL = 0;</code>
       */
      public static final int PERSONAL_VALUE = 0;
      /**
       * <code>GROUP = 1;</code>
       */
      public static final int GROUP_VALUE = 1;
      /**
       * <code>SERVER = 2;</code>
       */
      public static final int SERVER_VALUE = 2;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static MessageDirect valueOf(int value) {
        return forNumber(value);
      }

      public static MessageDirect forNumber(int value) {
        switch (value) {
          case 0: return PERSONAL;
          case 1: return GROUP;
          case 2: return SERVER;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<MessageDirect>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          MessageDirect> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<MessageDirect>() {
              public MessageDirect findValueByNumber(int number) {
                return MessageDirect.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return AckMessageProto.AckMessage.getDescriptor().getEnumTypes().get(0);
      }

      private static final MessageDirect[] VALUES = values();

      public static MessageDirect valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private MessageDirect(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:AckMessage.MessageDirect)
    }

    public static final int ID_FIELD_NUMBER = 1;
    private long id_;
    /**
     * <code>int64 id = 1;</code>
     */
    public long getId() {
      return id_;
    }

    public static final int CODE_FIELD_NUMBER = 2;
    private int code_;
    /**
     * <code>int32 code = 2;</code>
     */
    public int getCode() {
      return code_;
    }

    public static final int CONTENT_FIELD_NUMBER = 3;
    private volatile java.lang.Object content_;
    /**
     * <code>string content = 3;</code>
     */
    public java.lang.String getContent() {
      java.lang.Object ref = content_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        content_ = s;
        return s;
      }
    }
    /**
     * <code>string content = 3;</code>
     */
    public com.google.protobuf.ByteString
        getContentBytes() {
      java.lang.Object ref = content_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        content_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MATCHMESSAGEID_FIELD_NUMBER = 4;
    private long matchMessageId_;
    /**
     * <code>int64 matchMessageId = 4;</code>
     */
    public long getMatchMessageId() {
      return matchMessageId_;
    }

    public static final int TOUSERID_FIELD_NUMBER = 5;
    private int toUserId_;
    /**
     * <code>int32 toUserId = 5;</code>
     */
    public int getToUserId() {
      return toUserId_;
    }

    public static final int FROMUSERID_FIELD_NUMBER = 6;
    private int fromUserId_;
    /**
     * <code>int32 fromUserId = 6;</code>
     */
    public int getFromUserId() {
      return fromUserId_;
    }

    public static final int ASSOCIATEDGROUPID_FIELD_NUMBER = 7;
    private int associatedGroupId_;
    /**
     * <code>int32 associatedGroupId = 7;</code>
     */
    public int getAssociatedGroupId() {
      return associatedGroupId_;
    }

    public static final int MESSAGEDIRECT_FIELD_NUMBER = 8;
    private int messageDirect_;
    /**
     * <code>.AckMessage.MessageDirect messageDirect = 8;</code>
     */
    public int getMessageDirectValue() {
      return messageDirect_;
    }
    /**
     * <code>.AckMessage.MessageDirect messageDirect = 8;</code>
     */
    public AckMessageProto.AckMessage.MessageDirect getMessageDirect() {
      @SuppressWarnings("deprecation")
      AckMessageProto.AckMessage.MessageDirect result = AckMessageProto.AckMessage.MessageDirect.valueOf(messageDirect_);
      return result == null ? AckMessageProto.AckMessage.MessageDirect.UNRECOGNIZED : result;
    }

    public static final int MACHINESERIALNUMBER_FIELD_NUMBER = 9;
    private int machineSerialNumber_;
    /**
     * <code>int32 machineSerialNumber = 9;</code>
     */
    public int getMachineSerialNumber() {
      return machineSerialNumber_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0L) {
        output.writeInt64(1, id_);
      }
      if (code_ != 0) {
        output.writeInt32(2, code_);
      }
      if (!getContentBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, content_);
      }
      if (matchMessageId_ != 0L) {
        output.writeInt64(4, matchMessageId_);
      }
      if (toUserId_ != 0) {
        output.writeInt32(5, toUserId_);
      }
      if (fromUserId_ != 0) {
        output.writeInt32(6, fromUserId_);
      }
      if (associatedGroupId_ != 0) {
        output.writeInt32(7, associatedGroupId_);
      }
      if (messageDirect_ != AckMessageProto.AckMessage.MessageDirect.PERSONAL.getNumber()) {
        output.writeEnum(8, messageDirect_);
      }
      if (machineSerialNumber_ != 0) {
        output.writeInt32(9, machineSerialNumber_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, id_);
      }
      if (code_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, code_);
      }
      if (!getContentBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, content_);
      }
      if (matchMessageId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, matchMessageId_);
      }
      if (toUserId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, toUserId_);
      }
      if (fromUserId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, fromUserId_);
      }
      if (associatedGroupId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, associatedGroupId_);
      }
      if (messageDirect_ != AckMessageProto.AckMessage.MessageDirect.PERSONAL.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(8, messageDirect_);
      }
      if (machineSerialNumber_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(9, machineSerialNumber_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof AckMessageProto.AckMessage)) {
        return super.equals(obj);
      }
      AckMessageProto.AckMessage other = (AckMessageProto.AckMessage) obj;

      if (getId()
          != other.getId()) return false;
      if (getCode()
          != other.getCode()) return false;
      if (!getContent()
          .equals(other.getContent())) return false;
      if (getMatchMessageId()
          != other.getMatchMessageId()) return false;
      if (getToUserId()
          != other.getToUserId()) return false;
      if (getFromUserId()
          != other.getFromUserId()) return false;
      if (getAssociatedGroupId()
          != other.getAssociatedGroupId()) return false;
      if (messageDirect_ != other.messageDirect_) return false;
      if (getMachineSerialNumber()
          != other.getMachineSerialNumber()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getId());
      hash = (37 * hash) + CODE_FIELD_NUMBER;
      hash = (53 * hash) + getCode();
      hash = (37 * hash) + CONTENT_FIELD_NUMBER;
      hash = (53 * hash) + getContent().hashCode();
      hash = (37 * hash) + MATCHMESSAGEID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getMatchMessageId());
      hash = (37 * hash) + TOUSERID_FIELD_NUMBER;
      hash = (53 * hash) + getToUserId();
      hash = (37 * hash) + FROMUSERID_FIELD_NUMBER;
      hash = (53 * hash) + getFromUserId();
      hash = (37 * hash) + ASSOCIATEDGROUPID_FIELD_NUMBER;
      hash = (53 * hash) + getAssociatedGroupId();
      hash = (37 * hash) + MESSAGEDIRECT_FIELD_NUMBER;
      hash = (53 * hash) + messageDirect_;
      hash = (37 * hash) + MACHINESERIALNUMBER_FIELD_NUMBER;
      hash = (53 * hash) + getMachineSerialNumber();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static AckMessageProto.AckMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static AckMessageProto.AckMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static AckMessageProto.AckMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static AckMessageProto.AckMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static AckMessageProto.AckMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static AckMessageProto.AckMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static AckMessageProto.AckMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static AckMessageProto.AckMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static AckMessageProto.AckMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static AckMessageProto.AckMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static AckMessageProto.AckMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static AckMessageProto.AckMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(AckMessageProto.AckMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * class Person
     * </pre>
     *
     * Protobuf type {@code AckMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:AckMessage)
        AckMessageProto.AckMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return AckMessageProto.internal_static_AckMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return AckMessageProto.internal_static_AckMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                AckMessageProto.AckMessage.class, AckMessageProto.AckMessage.Builder.class);
      }

      // Construct using com.ghj.chat.protocol.AckMessageProto.AckMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = 0L;

        code_ = 0;

        content_ = "";

        matchMessageId_ = 0L;

        toUserId_ = 0;

        fromUserId_ = 0;

        associatedGroupId_ = 0;

        messageDirect_ = 0;

        machineSerialNumber_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return AckMessageProto.internal_static_AckMessage_descriptor;
      }

      @java.lang.Override
      public AckMessageProto.AckMessage getDefaultInstanceForType() {
        return AckMessageProto.AckMessage.getDefaultInstance();
      }

      @java.lang.Override
      public AckMessageProto.AckMessage build() {
        AckMessageProto.AckMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public AckMessageProto.AckMessage buildPartial() {
        AckMessageProto.AckMessage result = new AckMessageProto.AckMessage(this);
        result.id_ = id_;
        result.code_ = code_;
        result.content_ = content_;
        result.matchMessageId_ = matchMessageId_;
        result.toUserId_ = toUserId_;
        result.fromUserId_ = fromUserId_;
        result.associatedGroupId_ = associatedGroupId_;
        result.messageDirect_ = messageDirect_;
        result.machineSerialNumber_ = machineSerialNumber_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof AckMessageProto.AckMessage) {
          return mergeFrom((AckMessageProto.AckMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(AckMessageProto.AckMessage other) {
        if (other == AckMessageProto.AckMessage.getDefaultInstance()) return this;
        if (other.getId() != 0L) {
          setId(other.getId());
        }
        if (other.getCode() != 0) {
          setCode(other.getCode());
        }
        if (!other.getContent().isEmpty()) {
          content_ = other.content_;
          onChanged();
        }
        if (other.getMatchMessageId() != 0L) {
          setMatchMessageId(other.getMatchMessageId());
        }
        if (other.getToUserId() != 0) {
          setToUserId(other.getToUserId());
        }
        if (other.getFromUserId() != 0) {
          setFromUserId(other.getFromUserId());
        }
        if (other.getAssociatedGroupId() != 0) {
          setAssociatedGroupId(other.getAssociatedGroupId());
        }
        if (other.messageDirect_ != 0) {
          setMessageDirectValue(other.getMessageDirectValue());
        }
        if (other.getMachineSerialNumber() != 0) {
          setMachineSerialNumber(other.getMachineSerialNumber());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        AckMessageProto.AckMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (AckMessageProto.AckMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long id_ ;
      /**
       * <code>int64 id = 1;</code>
       */
      public long getId() {
        return id_;
      }
      /**
       * <code>int64 id = 1;</code>
       */
      public Builder setId(long value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = 0L;
        onChanged();
        return this;
      }

      private int code_ ;
      /**
       * <code>int32 code = 2;</code>
       */
      public int getCode() {
        return code_;
      }
      /**
       * <code>int32 code = 2;</code>
       */
      public Builder setCode(int value) {
        
        code_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 code = 2;</code>
       */
      public Builder clearCode() {
        
        code_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object content_ = "";
      /**
       * <code>string content = 3;</code>
       */
      public java.lang.String getContent() {
        java.lang.Object ref = content_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          content_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string content = 3;</code>
       */
      public com.google.protobuf.ByteString
          getContentBytes() {
        java.lang.Object ref = content_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          content_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string content = 3;</code>
       */
      public Builder setContent(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        content_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string content = 3;</code>
       */
      public Builder clearContent() {
        
        content_ = getDefaultInstance().getContent();
        onChanged();
        return this;
      }
      /**
       * <code>string content = 3;</code>
       */
      public Builder setContentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        content_ = value;
        onChanged();
        return this;
      }

      private long matchMessageId_ ;
      /**
       * <code>int64 matchMessageId = 4;</code>
       */
      public long getMatchMessageId() {
        return matchMessageId_;
      }
      /**
       * <code>int64 matchMessageId = 4;</code>
       */
      public Builder setMatchMessageId(long value) {
        
        matchMessageId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 matchMessageId = 4;</code>
       */
      public Builder clearMatchMessageId() {
        
        matchMessageId_ = 0L;
        onChanged();
        return this;
      }

      private int toUserId_ ;
      /**
       * <code>int32 toUserId = 5;</code>
       */
      public int getToUserId() {
        return toUserId_;
      }
      /**
       * <code>int32 toUserId = 5;</code>
       */
      public Builder setToUserId(int value) {
        
        toUserId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 toUserId = 5;</code>
       */
      public Builder clearToUserId() {
        
        toUserId_ = 0;
        onChanged();
        return this;
      }

      private int fromUserId_ ;
      /**
       * <code>int32 fromUserId = 6;</code>
       */
      public int getFromUserId() {
        return fromUserId_;
      }
      /**
       * <code>int32 fromUserId = 6;</code>
       */
      public Builder setFromUserId(int value) {
        
        fromUserId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 fromUserId = 6;</code>
       */
      public Builder clearFromUserId() {
        
        fromUserId_ = 0;
        onChanged();
        return this;
      }

      private int associatedGroupId_ ;
      /**
       * <code>int32 associatedGroupId = 7;</code>
       */
      public int getAssociatedGroupId() {
        return associatedGroupId_;
      }
      /**
       * <code>int32 associatedGroupId = 7;</code>
       */
      public Builder setAssociatedGroupId(int value) {
        
        associatedGroupId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 associatedGroupId = 7;</code>
       */
      public Builder clearAssociatedGroupId() {
        
        associatedGroupId_ = 0;
        onChanged();
        return this;
      }

      private int messageDirect_ = 0;
      /**
       * <code>.AckMessage.MessageDirect messageDirect = 8;</code>
       */
      public int getMessageDirectValue() {
        return messageDirect_;
      }
      /**
       * <code>.AckMessage.MessageDirect messageDirect = 8;</code>
       */
      public Builder setMessageDirectValue(int value) {
        messageDirect_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.AckMessage.MessageDirect messageDirect = 8;</code>
       */
      public AckMessageProto.AckMessage.MessageDirect getMessageDirect() {
        @SuppressWarnings("deprecation")
        AckMessageProto.AckMessage.MessageDirect result = AckMessageProto.AckMessage.MessageDirect.valueOf(messageDirect_);
        return result == null ? AckMessageProto.AckMessage.MessageDirect.UNRECOGNIZED : result;
      }
      /**
       * <code>.AckMessage.MessageDirect messageDirect = 8;</code>
       */
      public Builder setMessageDirect(AckMessageProto.AckMessage.MessageDirect value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        messageDirect_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.AckMessage.MessageDirect messageDirect = 8;</code>
       */
      public Builder clearMessageDirect() {
        
        messageDirect_ = 0;
        onChanged();
        return this;
      }

      private int machineSerialNumber_ ;
      /**
       * <code>int32 machineSerialNumber = 9;</code>
       */
      public int getMachineSerialNumber() {
        return machineSerialNumber_;
      }
      /**
       * <code>int32 machineSerialNumber = 9;</code>
       */
      public Builder setMachineSerialNumber(int value) {
        
        machineSerialNumber_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 machineSerialNumber = 9;</code>
       */
      public Builder clearMachineSerialNumber() {
        
        machineSerialNumber_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:AckMessage)
    }

    // @@protoc_insertion_point(class_scope:AckMessage)
    private static final AckMessageProto.AckMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new AckMessageProto.AckMessage();
    }

    public static AckMessageProto.AckMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AckMessage>
        PARSER = new com.google.protobuf.AbstractParser<AckMessage>() {
      @java.lang.Override
      public AckMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AckMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<AckMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AckMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public AckMessageProto.AckMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AckMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AckMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021ack_message.proto\"\225\002\n\nAckMessage\022\n\n\002id" +
      "\030\001 \001(\003\022\014\n\004code\030\002 \001(\005\022\017\n\007content\030\003 \001(\t\022\026\n" +
      "\016matchMessageId\030\004 \001(\003\022\020\n\010toUserId\030\005 \001(\005\022" +
      "\022\n\nfromUserId\030\006 \001(\005\022\031\n\021associatedGroupId" +
      "\030\007 \001(\005\0220\n\rmessageDirect\030\010 \001(\0162\031.AckMessa" +
      "ge.MessageDirect\022\033\n\023machineSerialNumber\030" +
      "\t \001(\005\"4\n\rMessageDirect\022\014\n\010PERSONAL\020\000\022\t\n\005" +
      "GROUP\020\001\022\n\n\006SERVER\020\002B\023\n\000B\017AckMessageProto" +
      "b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_AckMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_AckMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AckMessage_descriptor,
        new java.lang.String[] { "Id", "Code", "Content", "MatchMessageId", "ToUserId", "FromUserId", "AssociatedGroupId", "MessageDirect", "MachineSerialNumber", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
