// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: notify_message.proto

package com.ghj.chat.protocol;

public final class NotifyMessageProto {
  private NotifyMessageProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface NotifyMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:NotifyMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 id = 1;</code>
     */
    long getId();

    /**
     * <code>int32 code = 2;</code>
     */
    int getCode();

    /**
     * <code>string content = 3;</code>
     */
    String getContent();
    /**
     * <code>string content = 3;</code>
     */
    com.google.protobuf.ByteString
        getContentBytes();

    /**
     * <code>repeated int64 matchMessageIds = 4;</code>
     */
    java.util.List<Long> getMatchMessageIdsList();
    /**
     * <code>repeated int64 matchMessageIds = 4;</code>
     */
    int getMatchMessageIdsCount();
    /**
     * <code>repeated int64 matchMessageIds = 4;</code>
     */
    long getMatchMessageIds(int index);

    /**
     * <code>repeated int32 toUserIds = 5;</code>
     */
    java.util.List<Integer> getToUserIdsList();
    /**
     * <code>repeated int32 toUserIds = 5;</code>
     */
    int getToUserIdsCount();
    /**
     * <code>repeated int32 toUserIds = 5;</code>
     */
    int getToUserIds(int index);
  }
  /**
   * <pre>
   * class Person
   * </pre>
   *
   * Protobuf type {@code NotifyMessage}
   */
  public  static final class NotifyMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:NotifyMessage)
      NotifyMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use NotifyMessage.newBuilder() to construct.
    private NotifyMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private NotifyMessage() {
      content_ = "";
      matchMessageIds_ = emptyLongList();
      toUserIds_ = emptyIntList();
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new NotifyMessage();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private NotifyMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              id_ = input.readInt64();
              break;
            }
            case 16: {

              code_ = input.readInt32();
              break;
            }
            case 26: {
              String s = input.readStringRequireUtf8();

              content_ = s;
              break;
            }
            case 32: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                matchMessageIds_ = newLongList();
                mutable_bitField0_ |= 0x00000001;
              }
              matchMessageIds_.addLong(input.readInt64());
              break;
            }
            case 34: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000001) != 0) && input.getBytesUntilLimit() > 0) {
                matchMessageIds_ = newLongList();
                mutable_bitField0_ |= 0x00000001;
              }
              while (input.getBytesUntilLimit() > 0) {
                matchMessageIds_.addLong(input.readInt64());
              }
              input.popLimit(limit);
              break;
            }
            case 40: {
              if (!((mutable_bitField0_ & 0x00000002) != 0)) {
                toUserIds_ = newIntList();
                mutable_bitField0_ |= 0x00000002;
              }
              toUserIds_.addInt(input.readInt32());
              break;
            }
            case 42: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000002) != 0) && input.getBytesUntilLimit() > 0) {
                toUserIds_ = newIntList();
                mutable_bitField0_ |= 0x00000002;
              }
              while (input.getBytesUntilLimit() > 0) {
                toUserIds_.addInt(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          matchMessageIds_.makeImmutable(); // C
        }
        if (((mutable_bitField0_ & 0x00000002) != 0)) {
          toUserIds_.makeImmutable(); // C
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return NotifyMessageProto.internal_static_NotifyMessage_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return NotifyMessageProto.internal_static_NotifyMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              NotifyMessageProto.NotifyMessage.class, NotifyMessageProto.NotifyMessage.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private long id_;
    /**
     * <code>int64 id = 1;</code>
     */
    public long getId() {
      return id_;
    }

    public static final int CODE_FIELD_NUMBER = 2;
    private int code_;
    /**
     * <code>int32 code = 2;</code>
     */
    public int getCode() {
      return code_;
    }

    public static final int CONTENT_FIELD_NUMBER = 3;
    private volatile Object content_;
    /**
     * <code>string content = 3;</code>
     */
    public String getContent() {
      Object ref = content_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        content_ = s;
        return s;
      }
    }
    /**
     * <code>string content = 3;</code>
     */
    public com.google.protobuf.ByteString
        getContentBytes() {
      Object ref = content_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        content_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MATCHMESSAGEIDS_FIELD_NUMBER = 4;
    private com.google.protobuf.Internal.LongList matchMessageIds_;
    /**
     * <code>repeated int64 matchMessageIds = 4;</code>
     */
    public java.util.List<Long>
        getMatchMessageIdsList() {
      return matchMessageIds_;
    }
    /**
     * <code>repeated int64 matchMessageIds = 4;</code>
     */
    public int getMatchMessageIdsCount() {
      return matchMessageIds_.size();
    }
    /**
     * <code>repeated int64 matchMessageIds = 4;</code>
     */
    public long getMatchMessageIds(int index) {
      return matchMessageIds_.getLong(index);
    }
    private int matchMessageIdsMemoizedSerializedSize = -1;

    public static final int TOUSERIDS_FIELD_NUMBER = 5;
    private com.google.protobuf.Internal.IntList toUserIds_;
    /**
     * <code>repeated int32 toUserIds = 5;</code>
     */
    public java.util.List<Integer>
        getToUserIdsList() {
      return toUserIds_;
    }
    /**
     * <code>repeated int32 toUserIds = 5;</code>
     */
    public int getToUserIdsCount() {
      return toUserIds_.size();
    }
    /**
     * <code>repeated int32 toUserIds = 5;</code>
     */
    public int getToUserIds(int index) {
      return toUserIds_.getInt(index);
    }
    private int toUserIdsMemoizedSerializedSize = -1;

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (id_ != 0L) {
        output.writeInt64(1, id_);
      }
      if (code_ != 0) {
        output.writeInt32(2, code_);
      }
      if (!getContentBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, content_);
      }
      if (getMatchMessageIdsList().size() > 0) {
        output.writeUInt32NoTag(34);
        output.writeUInt32NoTag(matchMessageIdsMemoizedSerializedSize);
      }
      for (int i = 0; i < matchMessageIds_.size(); i++) {
        output.writeInt64NoTag(matchMessageIds_.getLong(i));
      }
      if (getToUserIdsList().size() > 0) {
        output.writeUInt32NoTag(42);
        output.writeUInt32NoTag(toUserIdsMemoizedSerializedSize);
      }
      for (int i = 0; i < toUserIds_.size(); i++) {
        output.writeInt32NoTag(toUserIds_.getInt(i));
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, id_);
      }
      if (code_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, code_);
      }
      if (!getContentBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, content_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < matchMessageIds_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt64SizeNoTag(matchMessageIds_.getLong(i));
        }
        size += dataSize;
        if (!getMatchMessageIdsList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        matchMessageIdsMemoizedSerializedSize = dataSize;
      }
      {
        int dataSize = 0;
        for (int i = 0; i < toUserIds_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(toUserIds_.getInt(i));
        }
        size += dataSize;
        if (!getToUserIdsList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        toUserIdsMemoizedSerializedSize = dataSize;
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof NotifyMessageProto.NotifyMessage)) {
        return super.equals(obj);
      }
      NotifyMessageProto.NotifyMessage other = (NotifyMessageProto.NotifyMessage) obj;

      if (getId()
          != other.getId()) return false;
      if (getCode()
          != other.getCode()) return false;
      if (!getContent()
          .equals(other.getContent())) return false;
      if (!getMatchMessageIdsList()
          .equals(other.getMatchMessageIdsList())) return false;
      if (!getToUserIdsList()
          .equals(other.getToUserIdsList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getId());
      hash = (37 * hash) + CODE_FIELD_NUMBER;
      hash = (53 * hash) + getCode();
      hash = (37 * hash) + CONTENT_FIELD_NUMBER;
      hash = (53 * hash) + getContent().hashCode();
      if (getMatchMessageIdsCount() > 0) {
        hash = (37 * hash) + MATCHMESSAGEIDS_FIELD_NUMBER;
        hash = (53 * hash) + getMatchMessageIdsList().hashCode();
      }
      if (getToUserIdsCount() > 0) {
        hash = (37 * hash) + TOUSERIDS_FIELD_NUMBER;
        hash = (53 * hash) + getToUserIdsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static NotifyMessageProto.NotifyMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static NotifyMessageProto.NotifyMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static NotifyMessageProto.NotifyMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static NotifyMessageProto.NotifyMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static NotifyMessageProto.NotifyMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static NotifyMessageProto.NotifyMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static NotifyMessageProto.NotifyMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static NotifyMessageProto.NotifyMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static NotifyMessageProto.NotifyMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static NotifyMessageProto.NotifyMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static NotifyMessageProto.NotifyMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static NotifyMessageProto.NotifyMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(NotifyMessageProto.NotifyMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * class Person
     * </pre>
     *
     * Protobuf type {@code NotifyMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:NotifyMessage)
        NotifyMessageProto.NotifyMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return NotifyMessageProto.internal_static_NotifyMessage_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return NotifyMessageProto.internal_static_NotifyMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                NotifyMessageProto.NotifyMessage.class, NotifyMessageProto.NotifyMessage.Builder.class);
      }

      // Construct using com.ghj.chat.protocol.NotifyMessageProto.NotifyMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        id_ = 0L;

        code_ = 0;

        content_ = "";

        matchMessageIds_ = emptyLongList();
        bitField0_ = (bitField0_ & ~0x00000001);
        toUserIds_ = emptyIntList();
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return NotifyMessageProto.internal_static_NotifyMessage_descriptor;
      }

      @Override
      public NotifyMessageProto.NotifyMessage getDefaultInstanceForType() {
        return NotifyMessageProto.NotifyMessage.getDefaultInstance();
      }

      @Override
      public NotifyMessageProto.NotifyMessage build() {
        NotifyMessageProto.NotifyMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public NotifyMessageProto.NotifyMessage buildPartial() {
        NotifyMessageProto.NotifyMessage result = new NotifyMessageProto.NotifyMessage(this);
        int from_bitField0_ = bitField0_;
        result.id_ = id_;
        result.code_ = code_;
        result.content_ = content_;
        if (((bitField0_ & 0x00000001) != 0)) {
          matchMessageIds_.makeImmutable();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.matchMessageIds_ = matchMessageIds_;
        if (((bitField0_ & 0x00000002) != 0)) {
          toUserIds_.makeImmutable();
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.toUserIds_ = toUserIds_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof NotifyMessageProto.NotifyMessage) {
          return mergeFrom((NotifyMessageProto.NotifyMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(NotifyMessageProto.NotifyMessage other) {
        if (other == NotifyMessageProto.NotifyMessage.getDefaultInstance()) return this;
        if (other.getId() != 0L) {
          setId(other.getId());
        }
        if (other.getCode() != 0) {
          setCode(other.getCode());
        }
        if (!other.getContent().isEmpty()) {
          content_ = other.content_;
          onChanged();
        }
        if (!other.matchMessageIds_.isEmpty()) {
          if (matchMessageIds_.isEmpty()) {
            matchMessageIds_ = other.matchMessageIds_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureMatchMessageIdsIsMutable();
            matchMessageIds_.addAll(other.matchMessageIds_);
          }
          onChanged();
        }
        if (!other.toUserIds_.isEmpty()) {
          if (toUserIds_.isEmpty()) {
            toUserIds_ = other.toUserIds_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureToUserIdsIsMutable();
            toUserIds_.addAll(other.toUserIds_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        NotifyMessageProto.NotifyMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (NotifyMessageProto.NotifyMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long id_ ;
      /**
       * <code>int64 id = 1;</code>
       */
      public long getId() {
        return id_;
      }
      /**
       * <code>int64 id = 1;</code>
       */
      public Builder setId(long value) {

        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 id = 1;</code>
       */
      public Builder clearId() {

        id_ = 0L;
        onChanged();
        return this;
      }

      private int code_ ;
      /**
       * <code>int32 code = 2;</code>
       */
      public int getCode() {
        return code_;
      }
      /**
       * <code>int32 code = 2;</code>
       */
      public Builder setCode(int value) {

        code_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 code = 2;</code>
       */
      public Builder clearCode() {

        code_ = 0;
        onChanged();
        return this;
      }

      private Object content_ = "";
      /**
       * <code>string content = 3;</code>
       */
      public String getContent() {
        Object ref = content_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          content_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string content = 3;</code>
       */
      public com.google.protobuf.ByteString
          getContentBytes() {
        Object ref = content_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          content_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string content = 3;</code>
       */
      public Builder setContent(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        content_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string content = 3;</code>
       */
      public Builder clearContent() {

        content_ = getDefaultInstance().getContent();
        onChanged();
        return this;
      }
      /**
       * <code>string content = 3;</code>
       */
      public Builder setContentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        content_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.Internal.LongList matchMessageIds_ = emptyLongList();
      private void ensureMatchMessageIdsIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          matchMessageIds_ = mutableCopy(matchMessageIds_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated int64 matchMessageIds = 4;</code>
       */
      public java.util.List<Long>
          getMatchMessageIdsList() {
        return ((bitField0_ & 0x00000001) != 0) ?
                 java.util.Collections.unmodifiableList(matchMessageIds_) : matchMessageIds_;
      }
      /**
       * <code>repeated int64 matchMessageIds = 4;</code>
       */
      public int getMatchMessageIdsCount() {
        return matchMessageIds_.size();
      }
      /**
       * <code>repeated int64 matchMessageIds = 4;</code>
       */
      public long getMatchMessageIds(int index) {
        return matchMessageIds_.getLong(index);
      }
      /**
       * <code>repeated int64 matchMessageIds = 4;</code>
       */
      public Builder setMatchMessageIds(
          int index, long value) {
        ensureMatchMessageIdsIsMutable();
        matchMessageIds_.setLong(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int64 matchMessageIds = 4;</code>
       */
      public Builder addMatchMessageIds(long value) {
        ensureMatchMessageIdsIsMutable();
        matchMessageIds_.addLong(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int64 matchMessageIds = 4;</code>
       */
      public Builder addAllMatchMessageIds(
          Iterable<? extends Long> values) {
        ensureMatchMessageIdsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, matchMessageIds_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int64 matchMessageIds = 4;</code>
       */
      public Builder clearMatchMessageIds() {
        matchMessageIds_ = emptyLongList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }

      private com.google.protobuf.Internal.IntList toUserIds_ = emptyIntList();
      private void ensureToUserIdsIsMutable() {
        if (!((bitField0_ & 0x00000002) != 0)) {
          toUserIds_ = mutableCopy(toUserIds_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <code>repeated int32 toUserIds = 5;</code>
       */
      public java.util.List<Integer>
          getToUserIdsList() {
        return ((bitField0_ & 0x00000002) != 0) ?
                 java.util.Collections.unmodifiableList(toUserIds_) : toUserIds_;
      }
      /**
       * <code>repeated int32 toUserIds = 5;</code>
       */
      public int getToUserIdsCount() {
        return toUserIds_.size();
      }
      /**
       * <code>repeated int32 toUserIds = 5;</code>
       */
      public int getToUserIds(int index) {
        return toUserIds_.getInt(index);
      }
      /**
       * <code>repeated int32 toUserIds = 5;</code>
       */
      public Builder setToUserIds(
          int index, int value) {
        ensureToUserIdsIsMutable();
        toUserIds_.setInt(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 toUserIds = 5;</code>
       */
      public Builder addToUserIds(int value) {
        ensureToUserIdsIsMutable();
        toUserIds_.addInt(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 toUserIds = 5;</code>
       */
      public Builder addAllToUserIds(
          Iterable<? extends Integer> values) {
        ensureToUserIdsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, toUserIds_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 toUserIds = 5;</code>
       */
      public Builder clearToUserIds() {
        toUserIds_ = emptyIntList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:NotifyMessage)
    }

    // @@protoc_insertion_point(class_scope:NotifyMessage)
    private static final NotifyMessageProto.NotifyMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new NotifyMessageProto.NotifyMessage();
    }

    public static NotifyMessageProto.NotifyMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<NotifyMessage>
        PARSER = new com.google.protobuf.AbstractParser<NotifyMessage>() {
      @Override
      public NotifyMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new NotifyMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<NotifyMessage> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<NotifyMessage> getParserForType() {
      return PARSER;
    }

    @Override
    public NotifyMessageProto.NotifyMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_NotifyMessage_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_NotifyMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\024notify_message.proto\"f\n\rNotifyMessage\022" +
      "\n\n\002id\030\001 \001(\003\022\014\n\004code\030\002 \001(\005\022\017\n\007content\030\003 \001" +
      "(\t\022\027\n\017matchMessageIds\030\004 \003(\003\022\021\n\ttoUserIds" +
      "\030\005 \003(\005B+\n\025com.ghj.chat.protocolB\022NotifyM" +
      "essageProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_NotifyMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_NotifyMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_NotifyMessage_descriptor,
        new String[] { "Id", "Code", "Content", "MatchMessageIds", "ToUserIds", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
