// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: request_message.proto

package com.ghj.chat.protocol;

public final class RequestMessageProto {
  private RequestMessageProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface RequestMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:RequestMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 id = 1;</code>
     */
    long getId();

    /**
     * <code>string loginName = 2;</code>
     */
    String getLoginName();
    /**
     * <code>string loginName = 2;</code>
     */
    com.google.protobuf.ByteString
        getLoginNameBytes();

    /**
     * <code>string nickName = 3;</code>
     */
    String getNickName();
    /**
     * <code>string nickName = 3;</code>
     */
    com.google.protobuf.ByteString
        getNickNameBytes();

    /**
     * <pre>
     *int32 对应java中的int
     * </pre>
     *
     * <code>int32 fromUserId = 4;</code>
     */
    int getFromUserId();

    /**
     * <pre>
     *optional 可以为空
     * </pre>
     *
     * <code>int32 toUserId = 5;</code>
     */
    int getToUserId();

    /**
     * <code>int32 toGroupId = 6;</code>
     */
    int getToGroupId();

    /**
     * <code>int32 messageTypeId = 7;</code>
     */
    int getMessageTypeId();

    /**
     * <code>string content = 8;</code>
     */
    String getContent();
    /**
     * <code>string content = 8;</code>
     */
    com.google.protobuf.ByteString
        getContentBytes();

    /**
     * <code>string token = 9;</code>
     */
    String getToken();
    /**
     * <code>string token = 9;</code>
     */
    com.google.protobuf.ByteString
        getTokenBytes();

    /**
     * <code>.RequestMessage.ClientBehavior clientBehavior = 10;</code>
     */
    int getClientBehaviorValue();
    /**
     * <code>.RequestMessage.ClientBehavior clientBehavior = 10;</code>
     */
    RequestMessageProto.RequestMessage.ClientBehavior getClientBehavior();

    /**
     * <code>.RequestMessage.MessageDirect messageDirect = 11;</code>
     */
    int getMessageDirectValue();
    /**
     * <code>.RequestMessage.MessageDirect messageDirect = 11;</code>
     */
    RequestMessageProto.RequestMessage.MessageDirect getMessageDirect();

    /**
     * <code>int64 deviceId = 12;</code>
     */
    long getDeviceId();
  }
  /**
   * <pre>
   * class Person
   * </pre>
   *
   * Protobuf type {@code RequestMessage}
   */
  public  static final class RequestMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:RequestMessage)
      RequestMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use RequestMessage.newBuilder() to construct.
    private RequestMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RequestMessage() {
      loginName_ = "";
      nickName_ = "";
      content_ = "";
      token_ = "";
      clientBehavior_ = 0;
      messageDirect_ = 0;
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new RequestMessage();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private RequestMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              id_ = input.readInt64();
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              loginName_ = s;
              break;
            }
            case 26: {
              String s = input.readStringRequireUtf8();

              nickName_ = s;
              break;
            }
            case 32: {

              fromUserId_ = input.readInt32();
              break;
            }
            case 40: {

              toUserId_ = input.readInt32();
              break;
            }
            case 48: {

              toGroupId_ = input.readInt32();
              break;
            }
            case 56: {

              messageTypeId_ = input.readInt32();
              break;
            }
            case 66: {
              String s = input.readStringRequireUtf8();

              content_ = s;
              break;
            }
            case 74: {
              String s = input.readStringRequireUtf8();

              token_ = s;
              break;
            }
            case 80: {
              int rawValue = input.readEnum();

              clientBehavior_ = rawValue;
              break;
            }
            case 88: {
              int rawValue = input.readEnum();

              messageDirect_ = rawValue;
              break;
            }
            case 96: {

              deviceId_ = input.readInt64();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return RequestMessageProto.internal_static_RequestMessage_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return RequestMessageProto.internal_static_RequestMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              RequestMessageProto.RequestMessage.class, RequestMessageProto.RequestMessage.Builder.class);
    }

    /**
     * Protobuf enum {@code RequestMessage.ClientBehavior}
     */
    public enum ClientBehavior
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>LOGIN = 0;</code>
       */
      LOGIN(0),
      /**
       * <code>PING = 1;</code>
       */
      PING(1),
      /**
       * <code>MESSAGE = 2;</code>
       */
      MESSAGE(2),
      /**
       * <code>LOGIN_OUT = 3;</code>
       */
      LOGIN_OUT(3),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>LOGIN = 0;</code>
       */
      public static final int LOGIN_VALUE = 0;
      /**
       * <code>PING = 1;</code>
       */
      public static final int PING_VALUE = 1;
      /**
       * <code>MESSAGE = 2;</code>
       */
      public static final int MESSAGE_VALUE = 2;
      /**
       * <code>LOGIN_OUT = 3;</code>
       */
      public static final int LOGIN_OUT_VALUE = 3;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @Deprecated
      public static ClientBehavior valueOf(int value) {
        return forNumber(value);
      }

      public static ClientBehavior forNumber(int value) {
        switch (value) {
          case 0: return LOGIN;
          case 1: return PING;
          case 2: return MESSAGE;
          case 3: return LOGIN_OUT;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<ClientBehavior>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          ClientBehavior> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<ClientBehavior>() {
              public ClientBehavior findValueByNumber(int number) {
                return ClientBehavior.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return RequestMessageProto.RequestMessage.getDescriptor().getEnumTypes().get(0);
      }

      private static final ClientBehavior[] VALUES = values();

      public static ClientBehavior valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private ClientBehavior(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:RequestMessage.ClientBehavior)
    }

    /**
     * Protobuf enum {@code RequestMessage.MessageDirect}
     */
    public enum MessageDirect
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>PERSONAL = 0;</code>
       */
      PERSONAL(0),
      /**
       * <code>GROUP = 1;</code>
       */
      GROUP(1),
      /**
       * <code>SERVER = 2;</code>
       */
      SERVER(2),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>PERSONAL = 0;</code>
       */
      public static final int PERSONAL_VALUE = 0;
      /**
       * <code>GROUP = 1;</code>
       */
      public static final int GROUP_VALUE = 1;
      /**
       * <code>SERVER = 2;</code>
       */
      public static final int SERVER_VALUE = 2;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @Deprecated
      public static MessageDirect valueOf(int value) {
        return forNumber(value);
      }

      public static MessageDirect forNumber(int value) {
        switch (value) {
          case 0: return PERSONAL;
          case 1: return GROUP;
          case 2: return SERVER;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<MessageDirect>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          MessageDirect> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<MessageDirect>() {
              public MessageDirect findValueByNumber(int number) {
                return MessageDirect.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return RequestMessageProto.RequestMessage.getDescriptor().getEnumTypes().get(1);
      }

      private static final MessageDirect[] VALUES = values();

      public static MessageDirect valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private MessageDirect(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:RequestMessage.MessageDirect)
    }

    public static final int ID_FIELD_NUMBER = 1;
    private long id_;
    /**
     * <code>int64 id = 1;</code>
     */
    public long getId() {
      return id_;
    }

    public static final int LOGINNAME_FIELD_NUMBER = 2;
    private volatile Object loginName_;
    /**
     * <code>string loginName = 2;</code>
     */
    public String getLoginName() {
      Object ref = loginName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        loginName_ = s;
        return s;
      }
    }
    /**
     * <code>string loginName = 2;</code>
     */
    public com.google.protobuf.ByteString
        getLoginNameBytes() {
      Object ref = loginName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        loginName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NICKNAME_FIELD_NUMBER = 3;
    private volatile Object nickName_;
    /**
     * <code>string nickName = 3;</code>
     */
    public String getNickName() {
      Object ref = nickName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        nickName_ = s;
        return s;
      }
    }
    /**
     * <code>string nickName = 3;</code>
     */
    public com.google.protobuf.ByteString
        getNickNameBytes() {
      Object ref = nickName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        nickName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FROMUSERID_FIELD_NUMBER = 4;
    private int fromUserId_;
    /**
     * <pre>
     *int32 对应java中的int
     * </pre>
     *
     * <code>int32 fromUserId = 4;</code>
     */
    public int getFromUserId() {
      return fromUserId_;
    }

    public static final int TOUSERID_FIELD_NUMBER = 5;
    private int toUserId_;
    /**
     * <pre>
     *optional 可以为空
     * </pre>
     *
     * <code>int32 toUserId = 5;</code>
     */
    public int getToUserId() {
      return toUserId_;
    }

    public static final int TOGROUPID_FIELD_NUMBER = 6;
    private int toGroupId_;
    /**
     * <code>int32 toGroupId = 6;</code>
     */
    public int getToGroupId() {
      return toGroupId_;
    }

    public static final int MESSAGETYPEID_FIELD_NUMBER = 7;
    private int messageTypeId_;
    /**
     * <code>int32 messageTypeId = 7;</code>
     */
    public int getMessageTypeId() {
      return messageTypeId_;
    }

    public static final int CONTENT_FIELD_NUMBER = 8;
    private volatile Object content_;
    /**
     * <code>string content = 8;</code>
     */
    public String getContent() {
      Object ref = content_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        content_ = s;
        return s;
      }
    }
    /**
     * <code>string content = 8;</code>
     */
    public com.google.protobuf.ByteString
        getContentBytes() {
      Object ref = content_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        content_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TOKEN_FIELD_NUMBER = 9;
    private volatile Object token_;
    /**
     * <code>string token = 9;</code>
     */
    public String getToken() {
      Object ref = token_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        token_ = s;
        return s;
      }
    }
    /**
     * <code>string token = 9;</code>
     */
    public com.google.protobuf.ByteString
        getTokenBytes() {
      Object ref = token_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        token_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CLIENTBEHAVIOR_FIELD_NUMBER = 10;
    private int clientBehavior_;
    /**
     * <code>.RequestMessage.ClientBehavior clientBehavior = 10;</code>
     */
    public int getClientBehaviorValue() {
      return clientBehavior_;
    }
    /**
     * <code>.RequestMessage.ClientBehavior clientBehavior = 10;</code>
     */
    public RequestMessageProto.RequestMessage.ClientBehavior getClientBehavior() {
      @SuppressWarnings("deprecation")
      RequestMessageProto.RequestMessage.ClientBehavior result = RequestMessageProto.RequestMessage.ClientBehavior.valueOf(clientBehavior_);
      return result == null ? RequestMessageProto.RequestMessage.ClientBehavior.UNRECOGNIZED : result;
    }

    public static final int MESSAGEDIRECT_FIELD_NUMBER = 11;
    private int messageDirect_;
    /**
     * <code>.RequestMessage.MessageDirect messageDirect = 11;</code>
     */
    public int getMessageDirectValue() {
      return messageDirect_;
    }
    /**
     * <code>.RequestMessage.MessageDirect messageDirect = 11;</code>
     */
    public RequestMessageProto.RequestMessage.MessageDirect getMessageDirect() {
      @SuppressWarnings("deprecation")
      RequestMessageProto.RequestMessage.MessageDirect result = RequestMessageProto.RequestMessage.MessageDirect.valueOf(messageDirect_);
      return result == null ? RequestMessageProto.RequestMessage.MessageDirect.UNRECOGNIZED : result;
    }

    public static final int DEVICEID_FIELD_NUMBER = 12;
    private long deviceId_;
    /**
     * <code>int64 deviceId = 12;</code>
     */
    public long getDeviceId() {
      return deviceId_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0L) {
        output.writeInt64(1, id_);
      }
      if (!getLoginNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, loginName_);
      }
      if (!getNickNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, nickName_);
      }
      if (fromUserId_ != 0) {
        output.writeInt32(4, fromUserId_);
      }
      if (toUserId_ != 0) {
        output.writeInt32(5, toUserId_);
      }
      if (toGroupId_ != 0) {
        output.writeInt32(6, toGroupId_);
      }
      if (messageTypeId_ != 0) {
        output.writeInt32(7, messageTypeId_);
      }
      if (!getContentBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, content_);
      }
      if (!getTokenBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 9, token_);
      }
      if (clientBehavior_ != RequestMessageProto.RequestMessage.ClientBehavior.LOGIN.getNumber()) {
        output.writeEnum(10, clientBehavior_);
      }
      if (messageDirect_ != RequestMessageProto.RequestMessage.MessageDirect.PERSONAL.getNumber()) {
        output.writeEnum(11, messageDirect_);
      }
      if (deviceId_ != 0L) {
        output.writeInt64(12, deviceId_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, id_);
      }
      if (!getLoginNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, loginName_);
      }
      if (!getNickNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, nickName_);
      }
      if (fromUserId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, fromUserId_);
      }
      if (toUserId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, toUserId_);
      }
      if (toGroupId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, toGroupId_);
      }
      if (messageTypeId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, messageTypeId_);
      }
      if (!getContentBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, content_);
      }
      if (!getTokenBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, token_);
      }
      if (clientBehavior_ != RequestMessageProto.RequestMessage.ClientBehavior.LOGIN.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(10, clientBehavior_);
      }
      if (messageDirect_ != RequestMessageProto.RequestMessage.MessageDirect.PERSONAL.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(11, messageDirect_);
      }
      if (deviceId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(12, deviceId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof RequestMessageProto.RequestMessage)) {
        return super.equals(obj);
      }
      RequestMessageProto.RequestMessage other = (RequestMessageProto.RequestMessage) obj;

      if (getId()
          != other.getId()) return false;
      if (!getLoginName()
          .equals(other.getLoginName())) return false;
      if (!getNickName()
          .equals(other.getNickName())) return false;
      if (getFromUserId()
          != other.getFromUserId()) return false;
      if (getToUserId()
          != other.getToUserId()) return false;
      if (getToGroupId()
          != other.getToGroupId()) return false;
      if (getMessageTypeId()
          != other.getMessageTypeId()) return false;
      if (!getContent()
          .equals(other.getContent())) return false;
      if (!getToken()
          .equals(other.getToken())) return false;
      if (clientBehavior_ != other.clientBehavior_) return false;
      if (messageDirect_ != other.messageDirect_) return false;
      if (getDeviceId()
          != other.getDeviceId()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getId());
      hash = (37 * hash) + LOGINNAME_FIELD_NUMBER;
      hash = (53 * hash) + getLoginName().hashCode();
      hash = (37 * hash) + NICKNAME_FIELD_NUMBER;
      hash = (53 * hash) + getNickName().hashCode();
      hash = (37 * hash) + FROMUSERID_FIELD_NUMBER;
      hash = (53 * hash) + getFromUserId();
      hash = (37 * hash) + TOUSERID_FIELD_NUMBER;
      hash = (53 * hash) + getToUserId();
      hash = (37 * hash) + TOGROUPID_FIELD_NUMBER;
      hash = (53 * hash) + getToGroupId();
      hash = (37 * hash) + MESSAGETYPEID_FIELD_NUMBER;
      hash = (53 * hash) + getMessageTypeId();
      hash = (37 * hash) + CONTENT_FIELD_NUMBER;
      hash = (53 * hash) + getContent().hashCode();
      hash = (37 * hash) + TOKEN_FIELD_NUMBER;
      hash = (53 * hash) + getToken().hashCode();
      hash = (37 * hash) + CLIENTBEHAVIOR_FIELD_NUMBER;
      hash = (53 * hash) + clientBehavior_;
      hash = (37 * hash) + MESSAGEDIRECT_FIELD_NUMBER;
      hash = (53 * hash) + messageDirect_;
      hash = (37 * hash) + DEVICEID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getDeviceId());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static RequestMessageProto.RequestMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static RequestMessageProto.RequestMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static RequestMessageProto.RequestMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static RequestMessageProto.RequestMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static RequestMessageProto.RequestMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static RequestMessageProto.RequestMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static RequestMessageProto.RequestMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static RequestMessageProto.RequestMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static RequestMessageProto.RequestMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static RequestMessageProto.RequestMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static RequestMessageProto.RequestMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static RequestMessageProto.RequestMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(RequestMessageProto.RequestMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * class Person
     * </pre>
     *
     * Protobuf type {@code RequestMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:RequestMessage)
        RequestMessageProto.RequestMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return RequestMessageProto.internal_static_RequestMessage_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return RequestMessageProto.internal_static_RequestMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                RequestMessageProto.RequestMessage.class, RequestMessageProto.RequestMessage.Builder.class);
      }

      // Construct using com.ghj.chat.protocol.RequestMessageProto.RequestMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        id_ = 0L;

        loginName_ = "";

        nickName_ = "";

        fromUserId_ = 0;

        toUserId_ = 0;

        toGroupId_ = 0;

        messageTypeId_ = 0;

        content_ = "";

        token_ = "";

        clientBehavior_ = 0;

        messageDirect_ = 0;

        deviceId_ = 0L;

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return RequestMessageProto.internal_static_RequestMessage_descriptor;
      }

      @Override
      public RequestMessageProto.RequestMessage getDefaultInstanceForType() {
        return RequestMessageProto.RequestMessage.getDefaultInstance();
      }

      @Override
      public RequestMessageProto.RequestMessage build() {
        RequestMessageProto.RequestMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public RequestMessageProto.RequestMessage buildPartial() {
        RequestMessageProto.RequestMessage result = new RequestMessageProto.RequestMessage(this);
        result.id_ = id_;
        result.loginName_ = loginName_;
        result.nickName_ = nickName_;
        result.fromUserId_ = fromUserId_;
        result.toUserId_ = toUserId_;
        result.toGroupId_ = toGroupId_;
        result.messageTypeId_ = messageTypeId_;
        result.content_ = content_;
        result.token_ = token_;
        result.clientBehavior_ = clientBehavior_;
        result.messageDirect_ = messageDirect_;
        result.deviceId_ = deviceId_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof RequestMessageProto.RequestMessage) {
          return mergeFrom((RequestMessageProto.RequestMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(RequestMessageProto.RequestMessage other) {
        if (other == RequestMessageProto.RequestMessage.getDefaultInstance()) return this;
        if (other.getId() != 0L) {
          setId(other.getId());
        }
        if (!other.getLoginName().isEmpty()) {
          loginName_ = other.loginName_;
          onChanged();
        }
        if (!other.getNickName().isEmpty()) {
          nickName_ = other.nickName_;
          onChanged();
        }
        if (other.getFromUserId() != 0) {
          setFromUserId(other.getFromUserId());
        }
        if (other.getToUserId() != 0) {
          setToUserId(other.getToUserId());
        }
        if (other.getToGroupId() != 0) {
          setToGroupId(other.getToGroupId());
        }
        if (other.getMessageTypeId() != 0) {
          setMessageTypeId(other.getMessageTypeId());
        }
        if (!other.getContent().isEmpty()) {
          content_ = other.content_;
          onChanged();
        }
        if (!other.getToken().isEmpty()) {
          token_ = other.token_;
          onChanged();
        }
        if (other.clientBehavior_ != 0) {
          setClientBehaviorValue(other.getClientBehaviorValue());
        }
        if (other.messageDirect_ != 0) {
          setMessageDirectValue(other.getMessageDirectValue());
        }
        if (other.getDeviceId() != 0L) {
          setDeviceId(other.getDeviceId());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        RequestMessageProto.RequestMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (RequestMessageProto.RequestMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long id_ ;
      /**
       * <code>int64 id = 1;</code>
       */
      public long getId() {
        return id_;
      }
      /**
       * <code>int64 id = 1;</code>
       */
      public Builder setId(long value) {

        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 id = 1;</code>
       */
      public Builder clearId() {

        id_ = 0L;
        onChanged();
        return this;
      }

      private Object loginName_ = "";
      /**
       * <code>string loginName = 2;</code>
       */
      public String getLoginName() {
        Object ref = loginName_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          loginName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string loginName = 2;</code>
       */
      public com.google.protobuf.ByteString
          getLoginNameBytes() {
        Object ref = loginName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          loginName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string loginName = 2;</code>
       */
      public Builder setLoginName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        loginName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string loginName = 2;</code>
       */
      public Builder clearLoginName() {

        loginName_ = getDefaultInstance().getLoginName();
        onChanged();
        return this;
      }
      /**
       * <code>string loginName = 2;</code>
       */
      public Builder setLoginNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        loginName_ = value;
        onChanged();
        return this;
      }

      private Object nickName_ = "";
      /**
       * <code>string nickName = 3;</code>
       */
      public String getNickName() {
        Object ref = nickName_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          nickName_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string nickName = 3;</code>
       */
      public com.google.protobuf.ByteString
          getNickNameBytes() {
        Object ref = nickName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          nickName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string nickName = 3;</code>
       */
      public Builder setNickName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        nickName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string nickName = 3;</code>
       */
      public Builder clearNickName() {

        nickName_ = getDefaultInstance().getNickName();
        onChanged();
        return this;
      }
      /**
       * <code>string nickName = 3;</code>
       */
      public Builder setNickNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        nickName_ = value;
        onChanged();
        return this;
      }

      private int fromUserId_ ;
      /**
       * <pre>
       *int32 对应java中的int
       * </pre>
       *
       * <code>int32 fromUserId = 4;</code>
       */
      public int getFromUserId() {
        return fromUserId_;
      }
      /**
       * <pre>
       *int32 对应java中的int
       * </pre>
       *
       * <code>int32 fromUserId = 4;</code>
       */
      public Builder setFromUserId(int value) {

        fromUserId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *int32 对应java中的int
       * </pre>
       *
       * <code>int32 fromUserId = 4;</code>
       */
      public Builder clearFromUserId() {

        fromUserId_ = 0;
        onChanged();
        return this;
      }

      private int toUserId_ ;
      /**
       * <pre>
       *optional 可以为空
       * </pre>
       *
       * <code>int32 toUserId = 5;</code>
       */
      public int getToUserId() {
        return toUserId_;
      }
      /**
       * <pre>
       *optional 可以为空
       * </pre>
       *
       * <code>int32 toUserId = 5;</code>
       */
      public Builder setToUserId(int value) {

        toUserId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *optional 可以为空
       * </pre>
       *
       * <code>int32 toUserId = 5;</code>
       */
      public Builder clearToUserId() {

        toUserId_ = 0;
        onChanged();
        return this;
      }

      private int toGroupId_ ;
      /**
       * <code>int32 toGroupId = 6;</code>
       */
      public int getToGroupId() {
        return toGroupId_;
      }
      /**
       * <code>int32 toGroupId = 6;</code>
       */
      public Builder setToGroupId(int value) {

        toGroupId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 toGroupId = 6;</code>
       */
      public Builder clearToGroupId() {

        toGroupId_ = 0;
        onChanged();
        return this;
      }

      private int messageTypeId_ ;
      /**
       * <code>int32 messageTypeId = 7;</code>
       */
      public int getMessageTypeId() {
        return messageTypeId_;
      }
      /**
       * <code>int32 messageTypeId = 7;</code>
       */
      public Builder setMessageTypeId(int value) {

        messageTypeId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 messageTypeId = 7;</code>
       */
      public Builder clearMessageTypeId() {

        messageTypeId_ = 0;
        onChanged();
        return this;
      }

      private Object content_ = "";
      /**
       * <code>string content = 8;</code>
       */
      public String getContent() {
        Object ref = content_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          content_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string content = 8;</code>
       */
      public com.google.protobuf.ByteString
          getContentBytes() {
        Object ref = content_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          content_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string content = 8;</code>
       */
      public Builder setContent(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        content_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string content = 8;</code>
       */
      public Builder clearContent() {

        content_ = getDefaultInstance().getContent();
        onChanged();
        return this;
      }
      /**
       * <code>string content = 8;</code>
       */
      public Builder setContentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        content_ = value;
        onChanged();
        return this;
      }

      private Object token_ = "";
      /**
       * <code>string token = 9;</code>
       */
      public String getToken() {
        Object ref = token_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          token_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string token = 9;</code>
       */
      public com.google.protobuf.ByteString
          getTokenBytes() {
        Object ref = token_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          token_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string token = 9;</code>
       */
      public Builder setToken(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        token_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string token = 9;</code>
       */
      public Builder clearToken() {

        token_ = getDefaultInstance().getToken();
        onChanged();
        return this;
      }
      /**
       * <code>string token = 9;</code>
       */
      public Builder setTokenBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        token_ = value;
        onChanged();
        return this;
      }

      private int clientBehavior_ = 0;
      /**
       * <code>.RequestMessage.ClientBehavior clientBehavior = 10;</code>
       */
      public int getClientBehaviorValue() {
        return clientBehavior_;
      }
      /**
       * <code>.RequestMessage.ClientBehavior clientBehavior = 10;</code>
       */
      public Builder setClientBehaviorValue(int value) {
        clientBehavior_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.RequestMessage.ClientBehavior clientBehavior = 10;</code>
       */
      public RequestMessageProto.RequestMessage.ClientBehavior getClientBehavior() {
        @SuppressWarnings("deprecation")
        RequestMessageProto.RequestMessage.ClientBehavior result = RequestMessageProto.RequestMessage.ClientBehavior.valueOf(clientBehavior_);
        return result == null ? RequestMessageProto.RequestMessage.ClientBehavior.UNRECOGNIZED : result;
      }
      /**
       * <code>.RequestMessage.ClientBehavior clientBehavior = 10;</code>
       */
      public Builder setClientBehavior(RequestMessageProto.RequestMessage.ClientBehavior value) {
        if (value == null) {
          throw new NullPointerException();
        }

        clientBehavior_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.RequestMessage.ClientBehavior clientBehavior = 10;</code>
       */
      public Builder clearClientBehavior() {

        clientBehavior_ = 0;
        onChanged();
        return this;
      }

      private int messageDirect_ = 0;
      /**
       * <code>.RequestMessage.MessageDirect messageDirect = 11;</code>
       */
      public int getMessageDirectValue() {
        return messageDirect_;
      }
      /**
       * <code>.RequestMessage.MessageDirect messageDirect = 11;</code>
       */
      public Builder setMessageDirectValue(int value) {
        messageDirect_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.RequestMessage.MessageDirect messageDirect = 11;</code>
       */
      public RequestMessageProto.RequestMessage.MessageDirect getMessageDirect() {
        @SuppressWarnings("deprecation")
        RequestMessageProto.RequestMessage.MessageDirect result = RequestMessageProto.RequestMessage.MessageDirect.valueOf(messageDirect_);
        return result == null ? RequestMessageProto.RequestMessage.MessageDirect.UNRECOGNIZED : result;
      }
      /**
       * <code>.RequestMessage.MessageDirect messageDirect = 11;</code>
       */
      public Builder setMessageDirect(RequestMessageProto.RequestMessage.MessageDirect value) {
        if (value == null) {
          throw new NullPointerException();
        }

        messageDirect_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.RequestMessage.MessageDirect messageDirect = 11;</code>
       */
      public Builder clearMessageDirect() {

        messageDirect_ = 0;
        onChanged();
        return this;
      }

      private long deviceId_ ;
      /**
       * <code>int64 deviceId = 12;</code>
       */
      public long getDeviceId() {
        return deviceId_;
      }
      /**
       * <code>int64 deviceId = 12;</code>
       */
      public Builder setDeviceId(long value) {

        deviceId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 deviceId = 12;</code>
       */
      public Builder clearDeviceId() {

        deviceId_ = 0L;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:RequestMessage)
    }

    // @@protoc_insertion_point(class_scope:RequestMessage)
    private static final RequestMessageProto.RequestMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new RequestMessageProto.RequestMessage();
    }

    public static RequestMessageProto.RequestMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RequestMessage>
        PARSER = new com.google.protobuf.AbstractParser<RequestMessage>() {
      @Override
      public RequestMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RequestMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<RequestMessage> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<RequestMessage> getParserForType() {
      return PARSER;
    }

    @Override
    public RequestMessageProto.RequestMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RequestMessage_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RequestMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\025request_message.proto\"\252\003\n\016RequestMessa" +
      "ge\022\n\n\002id\030\001 \001(\003\022\021\n\tloginName\030\002 \001(\t\022\020\n\010nic" +
      "kName\030\003 \001(\t\022\022\n\nfromUserId\030\004 \001(\005\022\020\n\010toUse" +
      "rId\030\005 \001(\005\022\021\n\ttoGroupId\030\006 \001(\005\022\025\n\rmessageT" +
      "ypeId\030\007 \001(\005\022\017\n\007content\030\010 \001(\t\022\r\n\005token\030\t " +
      "\001(\t\0226\n\016clientBehavior\030\n \001(\0162\036.RequestMes" +
      "sage.ClientBehavior\0224\n\rmessageDirect\030\013 \001" +
      "(\0162\035.RequestMessage.MessageDirect\022\020\n\010dev" +
      "iceId\030\014 \001(\003\"A\n\016ClientBehavior\022\t\n\005LOGIN\020\000" +
      "\022\010\n\004PING\020\001\022\013\n\007MESSAGE\020\002\022\r\n\tLOGIN_OUT\020\003\"4" +
      "\n\rMessageDirect\022\014\n\010PERSONAL\020\000\022\t\n\005GROUP\020\001" +
      "\022\n\n\006SERVER\020\002B,\n\025com.ghj.chat.protocolB\023R" +
      "equestMessageProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_RequestMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_RequestMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RequestMessage_descriptor,
        new String[] { "Id", "LoginName", "NickName", "FromUserId", "ToUserId", "ToGroupId", "MessageTypeId", "Content", "Token", "ClientBehavior", "MessageDirect", "DeviceId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
