// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: NowChat-Common/src/main/java/com/ghj/common/protocol/message.proto

package com.ghj.common.protocol;

public final class MessageProto {
  private MessageProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface messageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:message)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 id = 1;</code>
     */
    int getId();

    /**
     * <code>string loginName = 2;</code>
     */
    java.lang.String getLoginName();
    /**
     * <code>string loginName = 2;</code>
     */
    com.google.protobuf.ByteString
        getLoginNameBytes();

    /**
     * <code>string nickName = 3;</code>
     */
    java.lang.String getNickName();
    /**
     * <code>string nickName = 3;</code>
     */
    com.google.protobuf.ByteString
        getNickNameBytes();

    /**
     * <pre>
     *int32 对应java中的int
     * </pre>
     *
     * <code>int32 fromUserId = 4;</code>
     */
    int getFromUserId();

    /**
     * <pre>
     *optional 可以为空
     * </pre>
     *
     * <code>int32 toUserId = 5;</code>
     */
    int getToUserId();

    /**
     * <code>int32 toGroupId = 6;</code>
     */
    int getToGroupId();

    /**
     * <code>int32 messageTypeId = 7;</code>
     */
    int getMessageTypeId();

    /**
     * <code>string content = 8;</code>
     */
    java.lang.String getContent();
    /**
     * <code>string content = 8;</code>
     */
    com.google.protobuf.ByteString
        getContentBytes();

    /**
     * <code>string token = 9;</code>
     */
    java.lang.String getToken();
    /**
     * <code>string token = 9;</code>
     */
    com.google.protobuf.ByteString
        getTokenBytes();

    /**
     * <code>.message.ClientBehavior clientBehavior = 10;</code>
     */
    int getClientBehaviorValue();
    /**
     * <code>.message.ClientBehavior clientBehavior = 10;</code>
     */
    com.ghj.common.protocol.MessageProto.message.ClientBehavior getClientBehavior();

    /**
     * <code>.message.MessageDirect messageDirect = 11;</code>
     */
    int getMessageDirectValue();
    /**
     * <code>.message.MessageDirect messageDirect = 11;</code>
     */
    com.ghj.common.protocol.MessageProto.message.MessageDirect getMessageDirect();
  }
  /**
   * <pre>
   * class Person
   * </pre>
   *
   * Protobuf type {@code message}
   */
  public  static final class message extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:message)
      messageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use message.newBuilder() to construct.
    private message(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private message() {
      loginName_ = "";
      nickName_ = "";
      content_ = "";
      token_ = "";
      clientBehavior_ = 0;
      messageDirect_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new message();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private message(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              id_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              loginName_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              nickName_ = s;
              break;
            }
            case 32: {

              fromUserId_ = input.readInt32();
              break;
            }
            case 40: {

              toUserId_ = input.readInt32();
              break;
            }
            case 48: {

              toGroupId_ = input.readInt32();
              break;
            }
            case 56: {

              messageTypeId_ = input.readInt32();
              break;
            }
            case 66: {
              java.lang.String s = input.readStringRequireUtf8();

              content_ = s;
              break;
            }
            case 74: {
              java.lang.String s = input.readStringRequireUtf8();

              token_ = s;
              break;
            }
            case 80: {
              int rawValue = input.readEnum();

              clientBehavior_ = rawValue;
              break;
            }
            case 88: {
              int rawValue = input.readEnum();

              messageDirect_ = rawValue;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ghj.common.protocol.MessageProto.internal_static_message_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ghj.common.protocol.MessageProto.internal_static_message_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ghj.common.protocol.MessageProto.message.class, com.ghj.common.protocol.MessageProto.message.Builder.class);
    }

    /**
     * Protobuf enum {@code message.ClientBehavior}
     */
    public enum ClientBehavior
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>LOGIN = 0;</code>
       */
      LOGIN(0),
      /**
       * <code>PING = 1;</code>
       */
      PING(1),
      /**
       * <code>MESSAGE = 2;</code>
       */
      MESSAGE(2),
      /**
       * <code>LOGIN_OUT = 3;</code>
       */
      LOGIN_OUT(3),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>LOGIN = 0;</code>
       */
      public static final int LOGIN_VALUE = 0;
      /**
       * <code>PING = 1;</code>
       */
      public static final int PING_VALUE = 1;
      /**
       * <code>MESSAGE = 2;</code>
       */
      public static final int MESSAGE_VALUE = 2;
      /**
       * <code>LOGIN_OUT = 3;</code>
       */
      public static final int LOGIN_OUT_VALUE = 3;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static ClientBehavior valueOf(int value) {
        return forNumber(value);
      }

      public static ClientBehavior forNumber(int value) {
        switch (value) {
          case 0: return LOGIN;
          case 1: return PING;
          case 2: return MESSAGE;
          case 3: return LOGIN_OUT;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<ClientBehavior>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          ClientBehavior> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<ClientBehavior>() {
              public ClientBehavior findValueByNumber(int number) {
                return ClientBehavior.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.ghj.common.protocol.MessageProto.message.getDescriptor().getEnumTypes().get(0);
      }

      private static final ClientBehavior[] VALUES = values();

      public static ClientBehavior valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private ClientBehavior(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:message.ClientBehavior)
    }

    /**
     * Protobuf enum {@code message.MessageDirect}
     */
    public enum MessageDirect
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>PERSONAL = 0;</code>
       */
      PERSONAL(0),
      /**
       * <code>GROUP = 1;</code>
       */
      GROUP(1),
      /**
       * <code>SERVER = 2;</code>
       */
      SERVER(2),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>PERSONAL = 0;</code>
       */
      public static final int PERSONAL_VALUE = 0;
      /**
       * <code>GROUP = 1;</code>
       */
      public static final int GROUP_VALUE = 1;
      /**
       * <code>SERVER = 2;</code>
       */
      public static final int SERVER_VALUE = 2;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static MessageDirect valueOf(int value) {
        return forNumber(value);
      }

      public static MessageDirect forNumber(int value) {
        switch (value) {
          case 0: return PERSONAL;
          case 1: return GROUP;
          case 2: return SERVER;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<MessageDirect>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          MessageDirect> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<MessageDirect>() {
              public MessageDirect findValueByNumber(int number) {
                return MessageDirect.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.ghj.common.protocol.MessageProto.message.getDescriptor().getEnumTypes().get(1);
      }

      private static final MessageDirect[] VALUES = values();

      public static MessageDirect valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private MessageDirect(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:message.MessageDirect)
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int LOGINNAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object loginName_;
    /**
     * <code>string loginName = 2;</code>
     */
    public java.lang.String getLoginName() {
      java.lang.Object ref = loginName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        loginName_ = s;
        return s;
      }
    }
    /**
     * <code>string loginName = 2;</code>
     */
    public com.google.protobuf.ByteString
        getLoginNameBytes() {
      java.lang.Object ref = loginName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        loginName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NICKNAME_FIELD_NUMBER = 3;
    private volatile java.lang.Object nickName_;
    /**
     * <code>string nickName = 3;</code>
     */
    public java.lang.String getNickName() {
      java.lang.Object ref = nickName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        nickName_ = s;
        return s;
      }
    }
    /**
     * <code>string nickName = 3;</code>
     */
    public com.google.protobuf.ByteString
        getNickNameBytes() {
      java.lang.Object ref = nickName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nickName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FROMUSERID_FIELD_NUMBER = 4;
    private int fromUserId_;
    /**
     * <pre>
     *int32 对应java中的int
     * </pre>
     *
     * <code>int32 fromUserId = 4;</code>
     */
    public int getFromUserId() {
      return fromUserId_;
    }

    public static final int TOUSERID_FIELD_NUMBER = 5;
    private int toUserId_;
    /**
     * <pre>
     *optional 可以为空
     * </pre>
     *
     * <code>int32 toUserId = 5;</code>
     */
    public int getToUserId() {
      return toUserId_;
    }

    public static final int TOGROUPID_FIELD_NUMBER = 6;
    private int toGroupId_;
    /**
     * <code>int32 toGroupId = 6;</code>
     */
    public int getToGroupId() {
      return toGroupId_;
    }

    public static final int MESSAGETYPEID_FIELD_NUMBER = 7;
    private int messageTypeId_;
    /**
     * <code>int32 messageTypeId = 7;</code>
     */
    public int getMessageTypeId() {
      return messageTypeId_;
    }

    public static final int CONTENT_FIELD_NUMBER = 8;
    private volatile java.lang.Object content_;
    /**
     * <code>string content = 8;</code>
     */
    public java.lang.String getContent() {
      java.lang.Object ref = content_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        content_ = s;
        return s;
      }
    }
    /**
     * <code>string content = 8;</code>
     */
    public com.google.protobuf.ByteString
        getContentBytes() {
      java.lang.Object ref = content_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        content_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TOKEN_FIELD_NUMBER = 9;
    private volatile java.lang.Object token_;
    /**
     * <code>string token = 9;</code>
     */
    public java.lang.String getToken() {
      java.lang.Object ref = token_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        token_ = s;
        return s;
      }
    }
    /**
     * <code>string token = 9;</code>
     */
    public com.google.protobuf.ByteString
        getTokenBytes() {
      java.lang.Object ref = token_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        token_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CLIENTBEHAVIOR_FIELD_NUMBER = 10;
    private int clientBehavior_;
    /**
     * <code>.message.ClientBehavior clientBehavior = 10;</code>
     */
    public int getClientBehaviorValue() {
      return clientBehavior_;
    }
    /**
     * <code>.message.ClientBehavior clientBehavior = 10;</code>
     */
    public com.ghj.common.protocol.MessageProto.message.ClientBehavior getClientBehavior() {
      @SuppressWarnings("deprecation")
      com.ghj.common.protocol.MessageProto.message.ClientBehavior result = com.ghj.common.protocol.MessageProto.message.ClientBehavior.valueOf(clientBehavior_);
      return result == null ? com.ghj.common.protocol.MessageProto.message.ClientBehavior.UNRECOGNIZED : result;
    }

    public static final int MESSAGEDIRECT_FIELD_NUMBER = 11;
    private int messageDirect_;
    /**
     * <code>.message.MessageDirect messageDirect = 11;</code>
     */
    public int getMessageDirectValue() {
      return messageDirect_;
    }
    /**
     * <code>.message.MessageDirect messageDirect = 11;</code>
     */
    public com.ghj.common.protocol.MessageProto.message.MessageDirect getMessageDirect() {
      @SuppressWarnings("deprecation")
      com.ghj.common.protocol.MessageProto.message.MessageDirect result = com.ghj.common.protocol.MessageProto.message.MessageDirect.valueOf(messageDirect_);
      return result == null ? com.ghj.common.protocol.MessageProto.message.MessageDirect.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      if (!getLoginNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, loginName_);
      }
      if (!getNickNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, nickName_);
      }
      if (fromUserId_ != 0) {
        output.writeInt32(4, fromUserId_);
      }
      if (toUserId_ != 0) {
        output.writeInt32(5, toUserId_);
      }
      if (toGroupId_ != 0) {
        output.writeInt32(6, toGroupId_);
      }
      if (messageTypeId_ != 0) {
        output.writeInt32(7, messageTypeId_);
      }
      if (!getContentBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, content_);
      }
      if (!getTokenBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 9, token_);
      }
      if (clientBehavior_ != com.ghj.common.protocol.MessageProto.message.ClientBehavior.LOGIN.getNumber()) {
        output.writeEnum(10, clientBehavior_);
      }
      if (messageDirect_ != com.ghj.common.protocol.MessageProto.message.MessageDirect.PERSONAL.getNumber()) {
        output.writeEnum(11, messageDirect_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (!getLoginNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, loginName_);
      }
      if (!getNickNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, nickName_);
      }
      if (fromUserId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, fromUserId_);
      }
      if (toUserId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, toUserId_);
      }
      if (toGroupId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, toGroupId_);
      }
      if (messageTypeId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, messageTypeId_);
      }
      if (!getContentBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, content_);
      }
      if (!getTokenBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, token_);
      }
      if (clientBehavior_ != com.ghj.common.protocol.MessageProto.message.ClientBehavior.LOGIN.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(10, clientBehavior_);
      }
      if (messageDirect_ != com.ghj.common.protocol.MessageProto.message.MessageDirect.PERSONAL.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(11, messageDirect_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.ghj.common.protocol.MessageProto.message)) {
        return super.equals(obj);
      }
      com.ghj.common.protocol.MessageProto.message other = (com.ghj.common.protocol.MessageProto.message) obj;

      if (getId()
          != other.getId()) return false;
      if (!getLoginName()
          .equals(other.getLoginName())) return false;
      if (!getNickName()
          .equals(other.getNickName())) return false;
      if (getFromUserId()
          != other.getFromUserId()) return false;
      if (getToUserId()
          != other.getToUserId()) return false;
      if (getToGroupId()
          != other.getToGroupId()) return false;
      if (getMessageTypeId()
          != other.getMessageTypeId()) return false;
      if (!getContent()
          .equals(other.getContent())) return false;
      if (!getToken()
          .equals(other.getToken())) return false;
      if (clientBehavior_ != other.clientBehavior_) return false;
      if (messageDirect_ != other.messageDirect_) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + LOGINNAME_FIELD_NUMBER;
      hash = (53 * hash) + getLoginName().hashCode();
      hash = (37 * hash) + NICKNAME_FIELD_NUMBER;
      hash = (53 * hash) + getNickName().hashCode();
      hash = (37 * hash) + FROMUSERID_FIELD_NUMBER;
      hash = (53 * hash) + getFromUserId();
      hash = (37 * hash) + TOUSERID_FIELD_NUMBER;
      hash = (53 * hash) + getToUserId();
      hash = (37 * hash) + TOGROUPID_FIELD_NUMBER;
      hash = (53 * hash) + getToGroupId();
      hash = (37 * hash) + MESSAGETYPEID_FIELD_NUMBER;
      hash = (53 * hash) + getMessageTypeId();
      hash = (37 * hash) + CONTENT_FIELD_NUMBER;
      hash = (53 * hash) + getContent().hashCode();
      hash = (37 * hash) + TOKEN_FIELD_NUMBER;
      hash = (53 * hash) + getToken().hashCode();
      hash = (37 * hash) + CLIENTBEHAVIOR_FIELD_NUMBER;
      hash = (53 * hash) + clientBehavior_;
      hash = (37 * hash) + MESSAGEDIRECT_FIELD_NUMBER;
      hash = (53 * hash) + messageDirect_;
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.ghj.common.protocol.MessageProto.message parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ghj.common.protocol.MessageProto.message parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ghj.common.protocol.MessageProto.message parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ghj.common.protocol.MessageProto.message parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ghj.common.protocol.MessageProto.message parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ghj.common.protocol.MessageProto.message parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ghj.common.protocol.MessageProto.message parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ghj.common.protocol.MessageProto.message parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ghj.common.protocol.MessageProto.message parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.ghj.common.protocol.MessageProto.message parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.ghj.common.protocol.MessageProto.message parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.ghj.common.protocol.MessageProto.message parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.ghj.common.protocol.MessageProto.message prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * class Person
     * </pre>
     *
     * Protobuf type {@code message}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:message)
        com.ghj.common.protocol.MessageProto.messageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.ghj.common.protocol.MessageProto.internal_static_message_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.ghj.common.protocol.MessageProto.internal_static_message_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.ghj.common.protocol.MessageProto.message.class, com.ghj.common.protocol.MessageProto.message.Builder.class);
      }

      // Construct using com.ghj.common.protocol.MessageProto.message.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = 0;

        loginName_ = "";

        nickName_ = "";

        fromUserId_ = 0;

        toUserId_ = 0;

        toGroupId_ = 0;

        messageTypeId_ = 0;

        content_ = "";

        token_ = "";

        clientBehavior_ = 0;

        messageDirect_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.ghj.common.protocol.MessageProto.internal_static_message_descriptor;
      }

      @java.lang.Override
      public com.ghj.common.protocol.MessageProto.message getDefaultInstanceForType() {
        return com.ghj.common.protocol.MessageProto.message.getDefaultInstance();
      }

      @java.lang.Override
      public com.ghj.common.protocol.MessageProto.message build() {
        com.ghj.common.protocol.MessageProto.message result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.ghj.common.protocol.MessageProto.message buildPartial() {
        com.ghj.common.protocol.MessageProto.message result = new com.ghj.common.protocol.MessageProto.message(this);
        result.id_ = id_;
        result.loginName_ = loginName_;
        result.nickName_ = nickName_;
        result.fromUserId_ = fromUserId_;
        result.toUserId_ = toUserId_;
        result.toGroupId_ = toGroupId_;
        result.messageTypeId_ = messageTypeId_;
        result.content_ = content_;
        result.token_ = token_;
        result.clientBehavior_ = clientBehavior_;
        result.messageDirect_ = messageDirect_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.ghj.common.protocol.MessageProto.message) {
          return mergeFrom((com.ghj.common.protocol.MessageProto.message)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.ghj.common.protocol.MessageProto.message other) {
        if (other == com.ghj.common.protocol.MessageProto.message.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (!other.getLoginName().isEmpty()) {
          loginName_ = other.loginName_;
          onChanged();
        }
        if (!other.getNickName().isEmpty()) {
          nickName_ = other.nickName_;
          onChanged();
        }
        if (other.getFromUserId() != 0) {
          setFromUserId(other.getFromUserId());
        }
        if (other.getToUserId() != 0) {
          setToUserId(other.getToUserId());
        }
        if (other.getToGroupId() != 0) {
          setToGroupId(other.getToGroupId());
        }
        if (other.getMessageTypeId() != 0) {
          setMessageTypeId(other.getMessageTypeId());
        }
        if (!other.getContent().isEmpty()) {
          content_ = other.content_;
          onChanged();
        }
        if (!other.getToken().isEmpty()) {
          token_ = other.token_;
          onChanged();
        }
        if (other.clientBehavior_ != 0) {
          setClientBehaviorValue(other.getClientBehaviorValue());
        }
        if (other.messageDirect_ != 0) {
          setMessageDirectValue(other.getMessageDirectValue());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.ghj.common.protocol.MessageProto.message parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.ghj.common.protocol.MessageProto.message) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int id_ ;
      /**
       * <code>int32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 id = 1;</code>
       */
      public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object loginName_ = "";
      /**
       * <code>string loginName = 2;</code>
       */
      public java.lang.String getLoginName() {
        java.lang.Object ref = loginName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          loginName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string loginName = 2;</code>
       */
      public com.google.protobuf.ByteString
          getLoginNameBytes() {
        java.lang.Object ref = loginName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          loginName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string loginName = 2;</code>
       */
      public Builder setLoginName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        loginName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string loginName = 2;</code>
       */
      public Builder clearLoginName() {
        
        loginName_ = getDefaultInstance().getLoginName();
        onChanged();
        return this;
      }
      /**
       * <code>string loginName = 2;</code>
       */
      public Builder setLoginNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        loginName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object nickName_ = "";
      /**
       * <code>string nickName = 3;</code>
       */
      public java.lang.String getNickName() {
        java.lang.Object ref = nickName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          nickName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string nickName = 3;</code>
       */
      public com.google.protobuf.ByteString
          getNickNameBytes() {
        java.lang.Object ref = nickName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          nickName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string nickName = 3;</code>
       */
      public Builder setNickName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        nickName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string nickName = 3;</code>
       */
      public Builder clearNickName() {
        
        nickName_ = getDefaultInstance().getNickName();
        onChanged();
        return this;
      }
      /**
       * <code>string nickName = 3;</code>
       */
      public Builder setNickNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        nickName_ = value;
        onChanged();
        return this;
      }

      private int fromUserId_ ;
      /**
       * <pre>
       *int32 对应java中的int
       * </pre>
       *
       * <code>int32 fromUserId = 4;</code>
       */
      public int getFromUserId() {
        return fromUserId_;
      }
      /**
       * <pre>
       *int32 对应java中的int
       * </pre>
       *
       * <code>int32 fromUserId = 4;</code>
       */
      public Builder setFromUserId(int value) {
        
        fromUserId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *int32 对应java中的int
       * </pre>
       *
       * <code>int32 fromUserId = 4;</code>
       */
      public Builder clearFromUserId() {
        
        fromUserId_ = 0;
        onChanged();
        return this;
      }

      private int toUserId_ ;
      /**
       * <pre>
       *optional 可以为空
       * </pre>
       *
       * <code>int32 toUserId = 5;</code>
       */
      public int getToUserId() {
        return toUserId_;
      }
      /**
       * <pre>
       *optional 可以为空
       * </pre>
       *
       * <code>int32 toUserId = 5;</code>
       */
      public Builder setToUserId(int value) {
        
        toUserId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *optional 可以为空
       * </pre>
       *
       * <code>int32 toUserId = 5;</code>
       */
      public Builder clearToUserId() {
        
        toUserId_ = 0;
        onChanged();
        return this;
      }

      private int toGroupId_ ;
      /**
       * <code>int32 toGroupId = 6;</code>
       */
      public int getToGroupId() {
        return toGroupId_;
      }
      /**
       * <code>int32 toGroupId = 6;</code>
       */
      public Builder setToGroupId(int value) {
        
        toGroupId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 toGroupId = 6;</code>
       */
      public Builder clearToGroupId() {
        
        toGroupId_ = 0;
        onChanged();
        return this;
      }

      private int messageTypeId_ ;
      /**
       * <code>int32 messageTypeId = 7;</code>
       */
      public int getMessageTypeId() {
        return messageTypeId_;
      }
      /**
       * <code>int32 messageTypeId = 7;</code>
       */
      public Builder setMessageTypeId(int value) {
        
        messageTypeId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 messageTypeId = 7;</code>
       */
      public Builder clearMessageTypeId() {
        
        messageTypeId_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object content_ = "";
      /**
       * <code>string content = 8;</code>
       */
      public java.lang.String getContent() {
        java.lang.Object ref = content_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          content_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string content = 8;</code>
       */
      public com.google.protobuf.ByteString
          getContentBytes() {
        java.lang.Object ref = content_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          content_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string content = 8;</code>
       */
      public Builder setContent(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        content_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string content = 8;</code>
       */
      public Builder clearContent() {
        
        content_ = getDefaultInstance().getContent();
        onChanged();
        return this;
      }
      /**
       * <code>string content = 8;</code>
       */
      public Builder setContentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        content_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object token_ = "";
      /**
       * <code>string token = 9;</code>
       */
      public java.lang.String getToken() {
        java.lang.Object ref = token_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          token_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string token = 9;</code>
       */
      public com.google.protobuf.ByteString
          getTokenBytes() {
        java.lang.Object ref = token_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          token_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string token = 9;</code>
       */
      public Builder setToken(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        token_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string token = 9;</code>
       */
      public Builder clearToken() {
        
        token_ = getDefaultInstance().getToken();
        onChanged();
        return this;
      }
      /**
       * <code>string token = 9;</code>
       */
      public Builder setTokenBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        token_ = value;
        onChanged();
        return this;
      }

      private int clientBehavior_ = 0;
      /**
       * <code>.message.ClientBehavior clientBehavior = 10;</code>
       */
      public int getClientBehaviorValue() {
        return clientBehavior_;
      }
      /**
       * <code>.message.ClientBehavior clientBehavior = 10;</code>
       */
      public Builder setClientBehaviorValue(int value) {
        clientBehavior_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.message.ClientBehavior clientBehavior = 10;</code>
       */
      public com.ghj.common.protocol.MessageProto.message.ClientBehavior getClientBehavior() {
        @SuppressWarnings("deprecation")
        com.ghj.common.protocol.MessageProto.message.ClientBehavior result = com.ghj.common.protocol.MessageProto.message.ClientBehavior.valueOf(clientBehavior_);
        return result == null ? com.ghj.common.protocol.MessageProto.message.ClientBehavior.UNRECOGNIZED : result;
      }
      /**
       * <code>.message.ClientBehavior clientBehavior = 10;</code>
       */
      public Builder setClientBehavior(com.ghj.common.protocol.MessageProto.message.ClientBehavior value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        clientBehavior_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.message.ClientBehavior clientBehavior = 10;</code>
       */
      public Builder clearClientBehavior() {
        
        clientBehavior_ = 0;
        onChanged();
        return this;
      }

      private int messageDirect_ = 0;
      /**
       * <code>.message.MessageDirect messageDirect = 11;</code>
       */
      public int getMessageDirectValue() {
        return messageDirect_;
      }
      /**
       * <code>.message.MessageDirect messageDirect = 11;</code>
       */
      public Builder setMessageDirectValue(int value) {
        messageDirect_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.message.MessageDirect messageDirect = 11;</code>
       */
      public com.ghj.common.protocol.MessageProto.message.MessageDirect getMessageDirect() {
        @SuppressWarnings("deprecation")
        com.ghj.common.protocol.MessageProto.message.MessageDirect result = com.ghj.common.protocol.MessageProto.message.MessageDirect.valueOf(messageDirect_);
        return result == null ? com.ghj.common.protocol.MessageProto.message.MessageDirect.UNRECOGNIZED : result;
      }
      /**
       * <code>.message.MessageDirect messageDirect = 11;</code>
       */
      public Builder setMessageDirect(com.ghj.common.protocol.MessageProto.message.MessageDirect value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        messageDirect_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.message.MessageDirect messageDirect = 11;</code>
       */
      public Builder clearMessageDirect() {
        
        messageDirect_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:message)
    }

    // @@protoc_insertion_point(class_scope:message)
    private static final com.ghj.common.protocol.MessageProto.message DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.ghj.common.protocol.MessageProto.message();
    }

    public static com.ghj.common.protocol.MessageProto.message getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<message>
        PARSER = new com.google.protobuf.AbstractParser<message>() {
      @java.lang.Override
      public message parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new message(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<message> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<message> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.ghj.common.protocol.MessageProto.message getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_message_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_message_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\nBNowChat-Common/src/main/java/com/ghj/c" +
      "ommon/protocol/message.proto\"\203\003\n\007message" +
      "\022\n\n\002id\030\001 \001(\005\022\021\n\tloginName\030\002 \001(\t\022\020\n\010nickN" +
      "ame\030\003 \001(\t\022\022\n\nfromUserId\030\004 \001(\005\022\020\n\010toUserI" +
      "d\030\005 \001(\005\022\021\n\ttoGroupId\030\006 \001(\005\022\025\n\rmessageTyp" +
      "eId\030\007 \001(\005\022\017\n\007content\030\010 \001(\t\022\r\n\005token\030\t \001(" +
      "\t\022/\n\016clientBehavior\030\n \001(\0162\027.message.Clie" +
      "ntBehavior\022-\n\rmessageDirect\030\013 \001(\0162\026.mess" +
      "age.MessageDirect\"A\n\016ClientBehavior\022\t\n\005L" +
      "OGIN\020\000\022\010\n\004PING\020\001\022\013\n\007MESSAGE\020\002\022\r\n\tLOGIN_O" +
      "UT\020\003\"4\n\rMessageDirect\022\014\n\010PERSONAL\020\000\022\t\n\005G" +
      "ROUP\020\001\022\n\n\006SERVER\020\002B\'\n\027com.ghj.common.pro" +
      "tocolB\014MessageProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_message_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_message_descriptor,
        new java.lang.String[] { "Id", "LoginName", "NickName", "FromUserId", "ToUserId", "ToGroupId", "MessageTypeId", "Content", "Token", "ClientBehavior", "MessageDirect", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
